"""empty message

Revision ID: 90adcb3abe23
Revises: d2056b5a8585
Create Date: 2023-11-02 00:33:44.034872

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '90adcb3abe23'
down_revision = 'd2056b5a8585'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('height',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=250),
               existing_nullable=True)
        batch_op.alter_column('mass',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=250),
               existing_nullable=True)

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('diameter',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=250),
               existing_nullable=True)
        batch_op.alter_column('rotation_period',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=250),
               existing_nullable=True)
        batch_op.alter_column('gravity',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=250),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('gravity',
               existing_type=sa.String(length=250),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('rotation_period',
               existing_type=sa.String(length=250),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('diameter',
               existing_type=sa.String(length=250),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('mass',
               existing_type=sa.String(length=250),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('height',
               existing_type=sa.String(length=250),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
